### ISSUE TITLE
KataGo-raw does not point to valid commit atm

### ISSUE THREAD

**Issue by ed1d1a8d** [HumanCompatibleAI/go_attack#62]
I'm having trouble figuring out what commit `42892e` for KataGo-raw is — navigating to https://github.com/HumanCompatibleAI/KataGo-custom/tree/42892ea19b4256803ba7a0ff18d1096a84d11fe6 gives me a 404

_Originally posted by @tomtseng in https://github.com/HumanCompatibleAI/go_attack/issues/60#issuecomment-1312361371_

**Comment by tomtseng** [comment]
fixed, needed to pull the latest upstream changes from `lightvector/KataGo` into a branch in `HumanCompatibleAI/KataGo-custom`
